baseurl: ""
url: "http://ocheredklientov.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js
  - deploy
  - deploy-key.enc
  - deploy-key

title: "Очередь клиентов"
description: "Маркетинг до результата. Строим очередь клиентов, чтобы холодные продажи стали не нужны"
keywords: "бизнес, стартап, тестирование ниши, выбор ниши, предприниматель, запуск"
author: "Николай Воробьёв"

permalink: /:title/

vk_app_id: 5640654 # localhost:8000
yandex_metrika: 40647674 # ocheredklientov.com
google_analytics: UA-46456269-24 # ocheredklientov.com
facebook_pixel_id: 1064201373633710
vk_retarget_url: '//vk.com/rtrg?r=yLmG8tDKnrJpNjbZg0ib36SxPyI3YiYK7nAHipb4l/GiBxbnDXVfDBG3p3ero0E5PytT2tnzCxIkS1tAguicD6Uc3LFTBH2AMO*c7kiFjfnLWTUf6I0iyy4/6Up0h09*yZICzdLUHk01F*nc*A0gfq0ae8nHKS0YbyEfB6A9scs-&pixel_id=1000037662'

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
